version: "3"
services:
  core:
    build: ./app/docker/python/
    volumes:
      - .:/root
    command: gunicorn -w 4 --timeout 120 -b 0.0.0.0:8050 app.app:server # deploy
    environment:
      - PYTHONUNBUFFERED=True
    ports:
      - 8052:8050